package postgres_test

import (
	"sync"
	"testing"

	"github.com/omarluq/cord"
	"github.com/omarluq/cord/internal/storage"
	"github.com/omarluq/cord/internal/storage/postgres"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestMigratePreflightsNewerSchema verifies that migration rejects a newer persisted schema.
func TestMigratePreflightsNewerSchema(t *testing.T) {
	t.Parallel()

	database := openPostgres(t, startPostgres(t))
	_, err := database.ExecContext(t.Context(), `CREATE TABLE cord_schema_migrations (
		id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		version_id BIGINT NOT NULL,
		is_applied BOOLEAN NOT NULL,
		tstamp TIMESTAMP NOT NULL DEFAULT now()
	)`)
	require.NoError(t, err)

	_, err = database.ExecContext(
		t.Context(),
		`INSERT INTO cord_schema_migrations(version_id, is_applied) VALUES (5, true)`,
	)
	require.NoError(t, err)

	require.ErrorIs(t, postgres.Verify(t.Context(), database), storage.ErrSchemaNewer)
	err = postgres.Migrate(t.Context(), database)
	require.ErrorIs(t, err, storage.ErrSchemaNewer)

	var applicationTables int

	err = database.QueryRowContext(t.Context(), `SELECT count(*) FROM information_schema.tables
		WHERE table_schema = current_schema() AND table_name IN ('cord_runs', 'cord_nodes', 'cord_edges')`).
		Scan(&applicationTables)
	require.NoError(t, err)
	assert.Zero(t, applicationTables, "migration DDL must not run for a newer schema")
}

func TestConcurrentMigrations(t *testing.T) {
	t.Parallel()

	database := openPostgres(t, startPostgres(t))

	const constructors = 20

	results := make(chan error, constructors)

	var group sync.WaitGroup
	for range constructors {
		group.Go(func() {
			cordRuntime, err := cord.New(t.Context(), database)
			if err == nil {
				err = cordRuntime.Close()
			}

			results <- err
		})
	}

	group.Wait()
	close(results)

	for resultErr := range results {
		require.NoError(t, resultErr)
	}

	var migrations int

	const query = "SELECT count(*) FROM cord_schema_migrations WHERE version_id = 4"
	require.NoError(t, database.QueryRowContext(t.Context(), query).Scan(&migrations))
	assert.Equal(t, 1, migrations)
}
